sudo : required
services:
    - docker

before_install:
    - docker build -t pranshulaggarwal/reactapp -f Dockerfile.dev .
script:
    - docker run -e CI=true pranshulaggarwal/reactapp npm run test   